const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.LOS,
		C3.Behaviors.Pin,
		C3.Behaviors.Flash,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.ScriptsInEvents.Fas1_Event10,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.ScriptsInEvents.Fase2_Event14
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{CampoDeVisão: 0},
	{sensor: 0},
	{Fixar: 0},
	{Piscar: 0},
	{player: 0},
	{Teclado: 0},
	{CentrarEm: 0},
	{camera: 0},
	{Mouse: 0},
	{Sólido: 0},
	{chaoo: 0},
	{chaoo2: 0},
	{Sprite2: 0},
	{PlanoDeFundoEmBlocos: 0},
	{pared: 0},
	{fundoa: 0},
	{quina: 0},
	{fundob: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Senóide: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite7: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{Sprite29: 0},
	{Sprite31: 0},
	{limbo: 0},
	{Sprite32: 0},
	{Sprite28: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{start: 0},
	{CONTORLS: 0},
	{Sprite30: 0},
	{contorle: 0},
	{voltar: 0},
	{Sprite33: 0},
	{inimigoPatrulhero: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{gameOver: 0},
	{tenatardnv: 0},
	{menu: 0},
	{paredeParainimigo: 0},
	{paredeParainimigo2: 0},
	{Sprite: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{Sprite36: 0},
	{Sprite37: 0},
	{Sprite38: 0},
	{Sprite39: 0},
	{Sprite40: 0},
	{Sprite41: 0},
	{Sprite42: 0},
	{Sprite43: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{final: 0},
	{Sprite46: 0},
	{Sprite47: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{MoverPara: 0},
	{Sprite50: 0},
	{ativacao: 0},
	{Sprite51: 0},
	{Sprite52: 0},
	{morte: 0},
	{Sprite53: 0},
	{Sprite54: 0},
	{Sprite55: 0},
	{Sprite56: 0},
	{Sprite57: 0},
	{Sprite58: 0},
	{Sprite59: 0},
	{Áudio: 0},
	{ativa: 0},
	{Sprite60: 0},
	{Texto: 0},
	{Sprite61: 0},
	{msgText: 0}
];

self.InstanceType = {
	sensor: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	camera: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	chaoo: class extends self.ISpriteInstance {},
	chaoo2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	pared: class extends self.ISpriteInstance {},
	fundoa: class extends self.ISpriteInstance {},
	quina: class extends self.ISpriteInstance {},
	fundob: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	limbo: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	start: class extends self.ISpriteFontInstance {},
	CONTORLS: class extends self.ISpriteFontInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	contorle: class extends self.ISpriteFontInstance {},
	voltar: class extends self.ISpriteFontInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	inimigoPatrulhero: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	gameOver: class extends self.ISpriteFontInstance {},
	tenatardnv: class extends self.ISpriteFontInstance {},
	menu: class extends self.ISpriteFontInstance {},
	paredeParainimigo: class extends self.ISpriteInstance {},
	paredeParainimigo2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	final: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	ativacao: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	morte: class extends self.ISpriteInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	ativa: class extends self.ISpriteFontInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	msgText: class extends self.ITextInstance {}
}